### ISSUE TITLE
Network error when uploading test results to testrail

### ISSUE THREAD

**Issue by muthuels1** [gurock/automation-frameworks-integration#2]
I have used **trcli -y -c "trcli-config.yml" parse_junit -f "./report_sample/TEST-TestSuite.xml"**

![image](https://user-images.githubusercontent.com/97439483/204200881-1472b5c4-e4a8-4303-a090-650492aa935c.png)

**Comment by chrisfaragliaTestRail** [comment]
@muthuels1 this appears to be a network connectivity issue likely related to accessing the TestRail host URL defined in your TestRail CLI command. I would suggest debugging connectivity first by pinging the host or consulting with your organizations networking team. Reference [](https://cloud.google.com/blog/products/networking/using-netperf-and-ping-to-measure-network-latency)
