### ISSUE TITLE
Question on the Attaching files to the report

### ISSUE THREAD

**Issue by komalagrawal1991** [gurock/automation-frameworks-integration#3]
How to register the reporter in the file org.junit.platform.launcher.TestExecutionListener?
The png is not loading in the documentation.
<img width="1064" alt="Screenshot 2022-11-28 at 7 07 35 PM" src="https://user-images.githubusercontent.com/108717131/204291317-d0dc7dcc-6a71-4504-b30d-bca846a19b09.png">

**Comment by chrisfaragliaTestRail** [comment]
@komalagrawal1991 I am not fully understanding your question although I would revisit our recent video published on how to add attachment using the TestRail CLI. Feel free to post additional questions if you still are having issues.

See https://www.youtube.com/watch?v=7jKa818WruQ
